# Introduction to numpy ![](http://www.numpy.org/_static/numpy_logo.png)

NumPy is the fundamental package for scientific computing with Python

### Why not to use lists?

* Lists in Python are quite general, can have arbitrary objects as elements.

* Therefore, operations on lists are very slow

* Addition and scalar multiplication are defined for lists, but not what we want for numerical computation.

## Numpy arrays

Instead, we use numpy. Let's import it:

In [1]:
import numpy as np

The **core class** of NumPy is the `ndarray` (homogeneous n-dimensional array).

**Why it is useful**: Written in C, memory-efficient containers that provides fast numerical operations.

### Looking for help

* Documentation: https://docs.scipy.org/doc/numpy-1.11.0/reference/

* Interactive help

In [2]:
np.rollaxis??

Signature: np.rollaxis(a, axis, start=0)
Source:   
def rollaxis(a, axis, start=0):
    """
    Roll the specified axis backwards, until it lies in a given position.

    Parameters
    ----------
    a : ndarray
        Input array.
    axis : int
        The axis to roll backwards.  The positions of the other axes do not
        change relative to one another.
    start : int, optional
        The axis is rolled until it lies before this position.  The default,
        0, results in a "complete" roll.

    Returns
    -------
    res : ndarray
        For Numpy >= 1.10 a view of `a` is always returned. For earlier
        Numpy versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.

    See Also
    --------
    moveaxis : Move array axes to new positions.
    roll : Roll the elements of an array by a number of positions along a
        given axis.

    Examples
    --------
    >>> a = np.ones((3,4,5,6))
    >>> np

In [3]:
np.*space*?

np.linspace
np.logspace

* with NumPy: a built-in search engine

In [4]:
# np.lookfor('create array')

### Creating arrays

#### Manually

Using `array` function on a list:

In [5]:
a = np.array([3, 4, 5, 6])

In [6]:
a

array([3, 4, 5, 6])

The class is called

In [7]:
type(a)

numpy.ndarray

Scalar array

In [8]:
a0 = np.array(7)

In [9]:
a0.ndim

0

In [10]:
b = np.array([[10, 20, 30], [9, 8, 7]])

In [11]:
b

array([[10, 20, 30],
       [ 9,  8,  7]])

In [12]:
c = np.array([[[1], [2]], [[3], [4]]])

In [13]:
c.shape

(2, 2, 1)

#### Common mistakes

In [14]:
try:
    a = np.array(1,2,3,4) # WRONG, throws ValueError
except ValueError as e:
    print(e)

only 2 non-keyword arguments accepted


In [15]:
a = np.array([1,2,3,4]) # RIGHT

Do not use `np.ndarray` function to create an array

In [16]:
np.ndarray([1,2,3,4])

array([[[[  6.95113160e-310,   1.92806944e-316,   6.95113250e-310,
            6.95112111e-310],
         [  6.95113247e-310,   6.95112109e-310,   6.95113250e-310,
            6.95113251e-310],
         [  6.95113247e-310,   6.95112109e-310,   6.95113250e-310,
            6.95112109e-310]],

        [[  6.95113247e-310,   6.95112109e-310,   6.95113250e-310,
            6.95112109e-310],
         [  6.95113248e-310,   6.95112109e-310,   6.95113250e-310,
            6.95112109e-310],
         [  6.95113247e-310,   6.95112109e-310,   6.95113250e-310,
            6.95112109e-310]]]])

### Functions for creating arrays

#### evenly spaced

In [17]:
np.arange(1, 9, 2) # start, end (exclusive), step

array([1, 3, 5, 7])

#### by a number of points

In [18]:
np.linspace(0, 1, 6)   # start, end, num-points

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [19]:
np.logspace(-3, 2, 7)

array([  1.00000000e-03,   6.81292069e-03,   4.64158883e-02,
         3.16227766e-01,   2.15443469e+00,   1.46779927e+01,
         1.00000000e+02])

#### filled with specific value

* Zeros

In [20]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

* Ones

In [21]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

* Empty

In [22]:
np.empty([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

The function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

* Random numbers

In [23]:
np.random.rand(4)       # uniform in [0, 1]

array([ 0.70668673,  0.58083276,  0.84954009,  0.88399379])

In [24]:
np.random.randn(4)      # Gaussian

array([-0.52688476, -0.79335929, -0.00898846,  0.26343746])

#### Special cases

In [25]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Grid generation

* A common task is to generate a pair of arrays that represent data coordinates.
* When orthogonal 1D coordinate arrays already exist, NumPy's `meshgrid` function is very useful:

In [27]:
x = np.linspace(-5, 5, 3)
y = np.linspace(10, 40, 4)
x2d, y2d = np.meshgrid(x, y)
print(x2d)
print(y2d)

[[-5.  0.  5.]
 [-5.  0.  5.]
 [-5.  0.  5.]
 [-5.  0.  5.]]
[[ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]
 [ 40.  40.  40.]]


Other useful NumPy functions are `mgrid` and `ogrid`. If we wanted to reproduce the example above:

In [28]:
xx, yy = np.mgrid[-5:6:5, 10:41:10]
print(xx)
print(yy)

[[-5 -5 -5 -5]
 [ 0  0  0  0]
 [ 5  5  5  5]]
[[10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]


### Array attributes

In [29]:
b

array([[10, 20, 30],
       [ 9,  8,  7]])

#### ndarray.ndim
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

In [30]:
b.ndim

2

#### ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

In [31]:
b.shape

(2, 3)

#### ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.

In [32]:
b.size

6

Note that `size` is not equal to `len()`. The latter returns the length of the first dimension.

In [33]:
len(b)

2

#### ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [34]:
b.dtype

dtype('int64')

##### How to specify `dtype` for a new array?

In [35]:
np.array([123, 456, 789], dtype=np.complex256)

array([ 123.0+0.0j,  456.0+0.0j,  789.0+0.0j], dtype=complex256)

In [36]:
np.array([123, 456, 789], dtype='i')

array([123, 456, 789], dtype=int32)

## Array indexing

* Indices begin at 0, like other Python sequences (and C/C++)
* The fastest varying dimension is the last dimension! The outer level of the hierarchy is the first dimension.
* In 2D, the first dimension corresponds to rows, the second to columns.

In [37]:
a = np.arange(10, 100, 10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
a[2:9:3] # [start:end:step]

array([30, 60, 90])

In [39]:
a[:4]

array([10, 20, 30, 40])

In [40]:
# np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]

Other examples:

![](http://www.scipy-lectures.org/_images/numpy_indexing.png)

## Exercise

Create a 2D NumPy array from the following list and assign it to the variable "arr":

In [41]:
# [[2, 3.2, 5.5, -6.4, -2.2, 2.4],
#  [1, 22, 4, 0.1, 5.3, -9],
#  [3, 1, 2.1, 21, 1.1, -2]]

Can you guess what the following slices are equal to? Print them to check your understanding.

In [42]:
# a[:, 3]

In [43]:
# a[1:4, 0:4]

In [44]:
# a[1:, 2]

### Fancy indexing

NumPy arrays can be indexed with slices, but also with boolean or
integer arrays (masks)

#### Masks

In [45]:
a = np.random.randint(1, 100, 15) # array of 15 random integers between 1 and 100

In [46]:
mask = a % 3 == 0

In [47]:
mask

array([ True,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False,  True], dtype=bool)

In [48]:
a[mask]

array([66, 96, 99, 69, 42])

#### Integer sequences

In [49]:
a = np.linspace(0, 5, 11)
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [50]:
a[[1, 5, 7]]

array([ 0.5,  2.5,  3.5])

##### Aside: application to finite differences

In [51]:
x = np.arange(10)**2
delta_t = 10
print(x)

[ 0  1  4  9 16 25 36 49 64 81]


$\frac{\partial x}{\partial t} \approx \frac{x_{i+1} - x_{i}}{\Delta t}$

How to calculate this difference without a loop?

In [52]:
(x[1:] - x[:-1]) / delta_t

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7])

## Exercise?

* Consider an 4x5 2D array of negative integers:

In [53]:
a = np.arange(-100, 0, 5).reshape(4, 5)
a

array([[-100,  -95,  -90,  -85,  -80],
       [ -75,  -70,  -65,  -60,  -55],
       [ -50,  -45,  -40,  -35,  -30],
       [ -25,  -20,  -15,  -10,   -5]])

* Suppose you want to return an array `result`, which has the squared value when an element in array `a` is greater than `-90` and less than `-40`, and has ones when it is not.

In [54]:
result = np.zeros(a.shape, dtype=a.dtype)

* How would you fill this array according to the above condition?

Remember, loops are generally quite slow. So an "old-style" ("bruteforce") code can look like this:

In [55]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i, j] > -90 and a[i, j] < -40:
            result[i, j] = a[i, j]**2
        else:
            result[i, j] = 1

In [56]:
result

array([[   1,    1,    1, 7225, 6400],
       [5625, 4900, 4225, 3600, 3025],
       [2500, 2025,    1,    1,    1],
       [   1,    1,    1,    1,    1]])

But a more effective approach would be

In [57]:
condition =  (a > -90) & (a < -40)

In [58]:
print(condition)

[[False False False  True  True]
 [ True  True  True  True  True]
 [ True  True False False False]
 [False False False False False]]


In [59]:
result[condition] = a[condition]**2
result[~condition] = 1
print(result)

[[   1    1    1 7225 6400]
 [5625 4900 4225 3600 3025]
 [2500 2025    1    1    1]
 [   1    1    1    1    1]]


Or even a one-liner:

In [60]:
result = np.where(condition, a**2, 1)
print(result)

[[   1    1    1 7225 6400]
 [5625 4900 4225 3600 3025]
 [2500 2025    1    1    1]
 [   1    1    1    1    1]]


## Masked arrays - how to handle (propagating) missing values

![](../figures/masked_array.png)

All operations related to masked arrays live in `numpy.ma` submodule.

The simplest example of manual creation of a masked array:

In [61]:
a = np.ma.masked_array(data=[1, 2, 3],
                       mask=[True, True, False],
                       fill_value=-999)

How does it look?

In [62]:
a

masked_array(data = [-- -- 3],
             mask = [ True  True False],
       fill_value = -999)

Often, a task is to mask array depending on a criterion.

In [63]:
a = np.linspace(1, 15, 15)

In [64]:
masked_a = np.ma.masked_greater_equal(a, 11)

In [65]:
masked_a

masked_array(data = [1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 -- -- -- -- --],
             mask = [False False False False False False False False False False  True  True
  True  True  True],
       fill_value = 1e+20)

## Exercise

* Create a "data" array of 30 linearly spaced numbers in the interval (1, 15)
* Hint: use `np.linspace` or `np.arange` functions
* Create a condition - a True/False (boolean) array, corresponding to the masked values
* The data array should be masked where elements are
    - greater than 1
    - less or equal than 12
    - divisible by 2.
* Mask the array depending on the condition
* Hint: use `np.where` function

In [66]:
# Your code:
# arr = 

In [67]:
# Your code:
# condition = 

In [68]:
# masked_arr = np.ma.masked_where(condition, arr)
# print(masked_arr)

## Shape manipulation

In [69]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [70]:
print('{} <-- array'.format(a))
print('{} <-- its shape'.format(a.shape))

[[1 2 3]
 [4 5 6]] <-- array
(2, 3) <-- its shape


In [71]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [72]:
a.transpose((1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [73]:
a.repeat(4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6,
       6])

In [74]:
a.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
print('Old shape: {}'.format(a.shape))
print('New shape: {}'.format(a.reshape((3, 2)).shape))

Old shape: (2, 3)
New shape: (3, 2)


#### Add a dimension

In [76]:
a[..., np.newaxis].shape

(2, 3, 1)

## TODO: Exercise

[Trapezoidal integration?](https://github.com/SciTools/courses/blob/master/course_content/notebooks/numpy_intro.ipynb)

## Broadcasting

The fact that NumPy operates on an element-wise basis means that in principle arrays must always match one another's shape. However, NumPy will also helpfully "broadcast" dimensions when possible. 

![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)
[Image source](http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html)

## References
* [NumPy docs](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [SciPy lectures](http://www.scipy-lectures.org/)
* [NCAS Introduction to Scientific Computing Course](http://www.ceda.ac.uk/ncas-reading-2015/)